"""Model card generator — every number is read from a report file, never typed by hand."""
from __future__ import annotations

import json
from pathlib import Path

from . import dataset, gates, train


def _j(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def pct(x, d=1):
    return "—" if x is None else f"{100 * x:.{d}f}%"


def write(version: str = "1.0.0") -> str:
    md = train.MODELS_DIR / version
    ev, model, pol = _j(md / "evaluation_report.json"), _j(md / "model.json"), _j(md / "decision_policy.json")
    tr, par, adv, rep, an, rt = (_j(md / f) for f in ("training_run.json", "parity_report.json", "adversarial_report.json", "reproduce_report.json", "anomaly_report.json", "retrain_report.json"))
    ds_version = ev["dataset"].split("@")[1]
    manifest = _j(dataset.MANIFESTS / f"{dataset.NAME}-{ds_version}.json") or {}
    base_manifest = _j(dataset.MANIFESTS / f"{dataset.NAME}-1.0.0.json")
    bench, bench_src = gates.latest_benchmark(version)
    sus, sus_src = gates.sustained_benchmark()
    t, g = ev["test"], ev["gold"]
    L = []
    w = L.append
    w(f"# Model card — orbis-edge-risk {version}\n")
    w("> Generated by `python -m orbis_ml card` from the evaluation, parity, benchmark, adversarial and reproducibility reports in this directory. Measured values only; targets are labelled as targets.\n")
    w("## Model details\n")
    w(f"- **Task:** 4-class risk classification of one canonical endpoint event (`{model['feature_schema']}`, {model['input_dim']} features): `safe_normal`, `safe_unusual`, `suspicious_review`, `high_risk`.")
    w(f"- **Architecture:** {model['architecture']} — dense ReLU MLP, {sum(len(l['b']) + len(l['W']) * len(l['W'][0]) for l in model['layers'])} parameters, outputs logits.")
    w(f"- **Calibration / decision policy:** temperature T = {pol['temperature']}, τ_review = {pol['tau_review']} on P(suspicious)+P(high), τ_high = {pol['tau_high']} on P(high); abstain on unknown schema fields or normalised entropy ≥ {pol['abstain_entropy']}; abstained high-impact actions are escalated. Versioned separately as `{pol['version']}`.")
    w("- **Authority:** advisory only. Deterministic tenant policy owns authorization; the model may raise review, never lower it, and is ignored when unavailable, stale, incompatible or out of distribution.")
    w(f"- **Owner:** Orbis Relay ML. **Selected by:** lowest validation security cost among portable models (see `../baselines_report.md`).\n")
    w("## Intended use\n")
    w("Score sensitive actions proposed by AI agents, automations and people *before* they execute, on the endpoint (Core ML) or in the gateway (TypeScript port), so policy can route ambiguous or high-risk actions to a verified human with an explanation.\n")
    w("## Out of scope\n")
    w("- Final allow/deny decisions, DLP content inspection, malware detection, user surveillance.")
    w("- Raw content or raw destinations: the model only sees metadata and 16-hex destination hashes.")
    w("- Tenants or action vocabularies outside `endpoint-event/1` — those events abstain and fall back to policy.\n")
    w("## Training data\n")
    if base_manifest:
        w(f"- **Base dataset:** `{base_manifest['name']}@{base_manifest['version']}` — {base_manifest['row_count']:,} synthetic Northstar Cloud events over 28 days, {base_manifest['actors']} actors, {base_manifest['scenario_templates']} scenario templates; seed {base_manifest['seed']}; generator config `{base_manifest['generation_config_hash'][:12]}…`.")
        cd = base_manifest["class_distribution"]["train"]
        w(f"- **Train split:** {base_manifest['split_counts']['train']:,} rows ({', '.join(f'{k} {v:,}' for k, v in cd.items())}). Intentionally imbalanced; hard negatives {base_manifest['difficulty_breakdown']['hard_negative']:,}, adversarial {base_manifest['difficulty_breakdown']['adversarial']:,}.")
        w("- **Splits:** time-based (days 0–17 / 18–22 / 23–27), whole actor instances held out of train/val, template variant v2 and the disguised-classification template only in test. Leakage checks: " + base_manifest["leakage_checks"]["result"] + ".")
        w(f"- **Label noise:** {base_manifest['label_noise']:.0%} weak-label flips between the two safe classes (documented, kept in every split).")
    if version != "1.0.0" and manifest:
        w(f"- **Retraining data:** `{manifest['name']}@{manifest['version']}` adds {manifest['composition']['window_rows_labelled']:,} labelled rows from a 14-day production window ({', '.join(f'{k} {v}' for k, v in manifest['label_states'].items())}); label confidence weights {manifest['label_confidence_weights']}.")
    w("")
    w("## Evaluation\n")
    w("| Split | n | Mean security cost | Macro-F1 | High-risk escalation recall | Suspicious+high recall | False-escalation rate | Safe precision |")
    w("|---|---|---|---|---|---|---|---|")
    for s in ("val", "test"):
        e = ev[s]
        w(f"| {s} | {e['n']:,} | {e['mean_cost']:.4f} | {e['macro_f1']:.3f} | {pct(e['high_risk_escalation_recall'])} | {pct(e['risky_escalation_recall'])} | {pct(e['false_escalation_rate'], 2)} | {pct(e['safe_precision'], 2)} |")
    w(f"| gold (hand-authored, {g['n']} gated) | {g['n']} | — | — | {pct(g['high_risk_escalation_recall'])} | {pct(g['risky_escalation_recall'])} | {pct(g['false_escalation_rate'])} | {pct(g['safe_precision'])} |")
    if "window_holdout" in ev:
        e = ev["window_holdout"]
        w(f"| production window (un-reviewed) | {e['n']:,} | {e['mean_cost']:.4f} | {e['macro_f1']:.3f} | {pct(e['high_risk_escalation_recall'])} | {pct(e['risky_escalation_recall'])} | {pct(e['false_escalation_rate'], 2)} | {pct(e['safe_precision'], 2)} |")
    w("")
    w(f"Test risky PR-AUC {t.get('risky_pr_auc', 0):.4f} · ROC-AUC {t.get('risky_roc_auc', 0):.4f} · high-risk PR-AUC {t.get('high_risk_pr_auc', 0):.4f}. Gold hard-negative false-positive rate {pct(g['hard_negative_false_positive_rate'])}. Abstention rate on test {pct(t['abstention_rate'], 2)}.\n")
    w("**Test high-risk recall is held down by a documented limitation:** the test-only `disguised_classification` template (secret material labelled `internal`) is invisible to a metadata-only model. See *Known limitations*.\n")
    w("Per-class (test):\n")
    w("| Class | Precision | Recall | F1 | Support |")
    w("|---|---|---|---|---|")
    for k, v in t["per_class"].items():
        w(f"| {k} | {v['precision']:.3f} | {v['recall']:.3f} | {v['f1']:.3f} | {v['support']:,} |")
    w("\nWeakest required slices (test, risky escalation recall):\n")
    sl = sorted(((k, v) for k, v in ev["slices"].items() if v.get("risky_escalation_recall") is not None and v["risky"] >= 5), key=lambda kv: kv[1]["risky_escalation_recall"])[:6]
    w("| Slice | n | risky | escalation recall | false-escalation rate |")
    w("|---|---|---|---|---|")
    for k, v in sl:
        w(f"| {k} | {v['n']:,} | {v['risky']} | {pct(v['risky_escalation_recall'])} | {pct(v['false_escalation_rate'], 2)} |")
    w("")
    w("## Calibration\n")
    cc = ev.get("calibration_comparison")
    w(f"Test ECE {t['ece']:.4f}, Brier {t['brier']:.4f}." + (f" Without calibration ECE {cc['none']['ece']:.4f}; temperature {cc['temperature']['ece']:.4f}; one-vs-rest isotonic {cc['isotonic_ovr']['ece']:.4f} (not shipped: needs lookup tables on the edge)." if cc else ""))
    w("Thresholds were chosen on validation by minimising the security cost matrix, then moved toward escalation within a 5% cost tolerance, because validation only contains trained template variants.\n")
    w("## Runtime\n")
    if par:
        w("| Runtime | Artifact | Max |Δ prob| vs Python | Class agreement (test) | Parity |")
        w("|---|---|---|---|---|")
        for k, v in par["parity"].items():
            q = par["quantization"][k]
            w(f"| {k} | {q['artifact_bytes'] / 1024:.1f} KB | {v['max_abs_probability_delta']:.2e} | {pct(v['test_split_class_agreement'], 3)} | {'pass' if v['passed'] else 'fail'} (tol {v['tolerance']}) |")
        w("\n**Quantization decision:** ship FP32. FP16 stays inside its tolerance but saves only ~6 KB; weight-only INT8 exceeds the bounded probability delta and buys nothing measurable in latency for a 3.3k-parameter model.\n")
    if bench:
        wb, pp = bench["warm_batch1_us"], bench["pipeline_event_to_signal_us"]
        w(f"Measured on {bench['device']['cpu']} ({bench['device']['model']}), {bench['runtime']} / {bench['compute_units']} (`{bench_src}`):\n")
        w(f"- cold compile+load+first prediction **{bench['cold']['total_ms']:.1f} ms**; warm batch-1 **p50 {wb['p50']:.1f} µs, p95 {wb['p95']:.1f} µs, p99 {wb['p99']:.1f} µs** ({wb['throughput_per_s']:,.0f}/s on one thread)")
        w(f"- full event→features→anomaly→inference→decision pipeline **p50 {pp['p50']:.1f} µs, p95 {pp['p95']:.1f} µs**")
        w(f"- portable Swift forward pass p50 {bench['portable_swift_batch1_us']['p50']:.2f} µs — Core ML's per-call dispatch dominates a model this small")
        w(f"- memory: model load +{bench['memory_mb']['model_load_delta']:.1f} MB, process peak footprint {bench['memory_mb']['peak_footprint']:.1f} MB; idle CPU {bench['idle_cpu_percent']:.3f}%")
    if sus:
        s = sus["sustained"]
        w(f"- sustained {s['seconds'] / 60:.0f} min at {s['target_rate_eps']:.0f} events/s: {s['events']:,} events, pipeline p95 {s['pipeline_us']['p95']:.1f} µs, CPU {s['cpu_percent']:.2f}% of one core, footprint growth {s['footprint_growth_mb']:.2f} MB (`{sus_src}`)")
    w("- **Energy was not measured** (requires `powermetrics`/Instruments on a physical session); CPU time per 1k inferences is the proxy.\n")
    w("## Security evaluation\n")
    if adv:
        w(f"Adversarial suite: {adv['summary']['required_passed']}/{adv['summary']['required_total']} required cases pass.\n")
        w("| Case | Category | Status |")
        w("|---|---|---|")
        for c in adv["cases"]:
            w(f"| {c['name']} | {c['category']} | {c['status']} |")
        w("")
    if an:
        w(f"Behavioural anomaly (Model B, robust median/MAD per actor): ROC-AUC {an['robust_median_mad']['roc_auc']:.3f} / PR-AUC {an['robust_median_mad']['pr_auc']:.3f} on behavioural attacks vs Isolation Forest {an['isolation_forest']['roc_auc']:.3f} / {an['isolation_forest']['pr_auc']:.3f}. Auto-escalation on anomaly adopted: {an['fusion']['adopt_auto_escalation']}.\n")
    w("## Known limitations\n")
    w("- **Misclassified data defeats it.** If the event says `internal` and the payload is secret, a metadata model cannot know (gold g-k01/g-k02, test-only template). Classification must come from DLP/policy, not the agent.")
    w("- **Slow ramps are absorbed** by per-actor baselines (g-k03); the drift monitor is the complementary control.")
    w("- **Synthetic data.** Every training and test event is generated; real-tenant performance is unknown until shadow mode produces reviewed labels.")
    w("- **Gold set is no longer fully blind** for one behaviour: an unregistered-tool shortcut was found via a gold failure and fixed in the generator (see `error-analysis.md`).")
    w("- **Human feedback is weak supervision.** Approvals can be wrong; proxies are down-weighted and never applied online.")
    if adv:
        for c in adv["cases"]:
            if c["status"] == "documented_limitation":
                w(f"- Adversarial: *{c['name']}* — not caught by the edge model alone.")
    w("")
    w("## Lineage\n")
    w(f"- Dataset `{ev['dataset']}` · feature schema `{model['feature_schema']}` · MLflow run `{model.get('mlflow_run_id', '?')}`")
    if tr:
        w(f"- Git `{tr['git_sha']}` · seed {tr['random_seed']} · dependency lock `{tr['dependency_lock_sha256'][:12]}…` · trained on {tr['hardware']['cpu']} in {tr['final_fit_seconds']} s")
    if rep:
        w(f"- Reproducibility: dataset regenerated hash-identical = {rep['dataset_verification']['passed']}; retrained metric max delta {max(rep['retrained_metric_deltas'].values()):.1e} (tolerance {rep['tolerance']}); weights bit-identical = {rep['weights_bit_identical']}")
    w(f"- Artifact sha256: model.json `{ev['artifact_sha256']['model.json'][:16]}…`, decision_policy.json `{ev['artifact_sha256']['decision_policy.json'][:16]}…`")
    if rt:
        w(f"- Produced by the retraining pipeline from drift windows + review queue ({rt['review_queue']['reviewed']} analyst reviews, {rt['human_decision_proxies']} human-decision proxies). Status: {rt['status']}.")
    w("- Release gates: see `release_gate_report.json`.")
    text = "\n".join(L) + "\n"
    (md / "MODEL_CARD.md").write_text(text)
    return str(md / "MODEL_CARD.md")
