import CoreML
import XCTest
@testable import OrbisEndpointCore

/// Python ↔ Swift parity: features (exact categorical, 1e-9 floats), anomaly scores, model outputs,
/// decision policy and reason codes — all against fixtures generated by `ml/orbis_ml`.
final class FeatureParityTests: XCTestCase {
    func testFeatureNamesMatchSpec() throws {
        let spec = try Repo.json("fixtures/endpoint-events/feature-spec.json") as! [String: Any]
        XCTAssertEqual(spec["feature_schema"] as? String, EdgeFeatures.schema)
        XCTAssertEqual(spec["names"] as? [String], EdgeFeatures.names)
    }

    func testStreamsMatchPythonReference() throws {
        let doc = try Repo.json("fixtures/endpoint-events/feature-parity.json") as! [String: Any]
        let streams = doc["streams"] as! [[String: Any]]
        var vectors = 0
        for s in streams {
            let name = s["name"] as! String
            let events = s["events"] as! [[String: Any]]
            let expected = s["expected"] as! [[String: Any]]
            let state = FeatureState()
            for (e, exp) in zip(events, expected) {
                let ev = try EventSchema.validate(e)
                let x = EdgeFeatures.compute(ev, state)
                let an = EdgeFeatures.anomaly(ev, state)
                EdgeFeatures.update(ev, state)
                let ref = exp["features"] as! [Double]
                XCTAssertEqual(x.count, ref.count)
                for i in 0..<ref.count {
                    if abs(x[i] - ref[i]) > 1e-9 {
                        XCTFail("\(name) \(ev.eventId) feature \(EdgeFeatures.names[i]): swift \(x[i]) python \(ref[i])")
                        return
                    }
                }
                let ra = exp["anomaly"] as! [String: Any]
                XCTAssertEqual(an.sufficient, ra["sufficient"] as! Bool, "\(name) \(ev.eventId) anomaly sufficiency")
                XCTAssertEqual(an.score, ra["score"] as! Double, accuracy: 1e-9, "\(name) \(ev.eventId) anomaly score")
                let refTop = (ra["contributions"] as! [[String: Any]]).map { $0["feature"] as! String }
                XCTAssertEqual(an.contributions.map(\.feature), refTop, "\(name) \(ev.eventId) anomaly contributions")
                vectors += 1
            }
        }
        XCTAssertGreaterThan(vectors, 1000)
    }

    func testInvalidEventsAreRejectedOnTheSameField() throws {
        let doc = try Repo.json("fixtures/endpoint-events/feature-parity.json") as! [String: Any]
        for c in doc["invalid"] as! [[String: Any]] {
            XCTAssertThrowsError(try EventSchema.validate(c["event"] as! [String: Any]), c["name"] as! String) { err in
                XCTAssertEqual((err as? SchemaError)?.field, c["field"] as? String, c["name"] as! String)
            }
        }
    }

    func testDomainHashMatchesPython() {
        XCTAssertEqual(EventSchema.domainHash(" QuickScribe-AI.app "), "e00fd622626850a6")
        XCTAssertEqual(EventSchema.domainHash("example.org"), "bfabc37432958b06")
        XCTAssertEqual(EventSchema.domainHash(""), "")
    }
}

final class ModelParityTests: XCTestCase {
    struct Case { let x: [Double]; let logits: [Double]; let probs: [Double]; let cls: Int; let abstain: Bool; let reasons: [String]; let id: String }

    func cases() throws -> [Case] {
        let doc = try Repo.json("fixtures/parity/edge-risk-\(Repo.modelVersion).json") as! [String: Any]
        return (doc["cases"] as! [[String: Any]]).map {
            Case(x: $0["features"] as! [Double], logits: $0["logits"] as! [Double], probs: $0["probs"] as! [Double], cls: $0["class"] as! Int,
                 abstain: $0["abstain"] as! Bool, reasons: $0["reasons"] as! [String], id: $0["event_id"] as! String)
        }
    }

    func policy() throws -> DecisionPolicy { try DecisionPolicy.load(Data(contentsOf: Repo.modelDir.appendingPathComponent("decision_policy.json"))) }

    func testPortableSwiftMatchesPythonExactly() throws {
        let m = try PortableMLP(json: Data(contentsOf: Repo.modelDir.appendingPathComponent("model.json")))
        let p = try policy()
        for c in try cases() {
            let z = try m.logits(c.x)
            for i in 0..<4 { XCTAssertEqual(z[i], c.logits[i], accuracy: 1e-9, c.id) }
            let d = Decision.decide(logits: z, features: c.x, policy: p)
            XCTAssertEqual(d.cls, c.cls, c.id)
            XCTAssertEqual(d.abstain, c.abstain, c.id)
            for i in 0..<4 { XCTAssertEqual(d.probs[i], c.probs[i], accuracy: 1e-9, c.id) }
            XCTAssertEqual(Decision.reasons(c.x).map(\.code), c.reasons, c.id)
        }
    }

    func testCoreMLFP32WithinTolerance() throws {
        let compiled = try CoreMLRiskModel.compile(Repo.modelDir.appendingPathComponent("coreml/OrbisEdgeRisk-fp32.mlpackage"))
        defer { try? FileManager.default.removeItem(at: compiled) }
        let m = try CoreMLRiskModel(compiledURL: compiled)
        let p = try policy()
        var maxDelta = 0.0
        var agree = 0
        let cs = try cases()
        for c in cs {
            let d = Decision.decide(logits: try m.logits(c.x), features: c.x, policy: p)
            maxDelta = max(maxDelta, zip(d.probs, c.probs).map { abs($0 - $1) }.max()!)
            if d.cls == c.cls { agree += 1 }
        }
        XCTAssertLessThanOrEqual(maxDelta, 1e-4, "Core ML FP32 max probability delta")
        XCTAssertEqual(agree, cs.count, "class agreement")
    }

    func testIncompatibleFeatureSchemaIsRefused() throws {
        var obj = try JSONSerialization.jsonObject(with: Data(contentsOf: Repo.modelDir.appendingPathComponent("model.json"))) as! [String: Any]
        obj["feature_schema"] = "edge-features/0"
        XCTAssertThrowsError(try PortableMLP(json: JSONSerialization.data(withJSONObject: obj)))
    }
}
